[package]
name = "wasmtime-jni"
version = "0.1.0"
authors = ["Yuto Kawamura <kawamuray.dadada@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.17.0"
thiserror = "1.0.20"
anyhow = "1.0.31"
wasmtime = "0.19.0"
wasmtime-wasi = "0.19.1"
wasi-common = "0.19.1"
